-- ===========================
-- DIWBIKES Schema Setup
-- ===========================
CREATE SCHEMA IF NOT EXISTS person;
CREATE SCHEMA IF NOT EXISTS production;
CREATE SCHEMA IF NOT EXISTS sales;
CREATE SCHEMA IF NOT EXISTS humanresources;

-- ===========================
-- Person Tables
-- ===========================
CREATE TABLE IF NOT EXISTS person.person (
    person_id INTEGER NOT NULL,
    person_type CHAR(2) NOT NULL,
    title VARCHAR(8),
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    suffix VARCHAR(10),
    email_address VARCHAR(50),
    address_id INTEGER NULL,
    address_type_id INTEGER NULL,
    CHECK (person_type IS NULL OR UPPER(person_type) IN ('SC','VC','IN','EM','SP','GC'))
);
CREATE TABLE IF NOT EXISTS person.address (
    address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_line1 VARCHAR(60) NOT NULL,
    address_line2 VARCHAR(60),
    city VARCHAR(30) NOT NULL,
    state_province_id INTEGER NOT NULL,
    postal_code VARCHAR(15) NOT NULL,
    spatial_location TEXT,
    rowguid UUID NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS person.Address_Type(
    Address_Type_ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name Name NOT NULL,
    rowguid UUID  NOT NULL,
    ModifiedDate TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP
);

-- ===========================
-- Production Tables
-- ===========================

CREATE TABLE IF NOT EXISTS production.location (
    location_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    cost_rate NUMERIC(10,4) NOT NULL DEFAULT 0.00 CHECK (cost_rate >= 0.00),
    availability NUMERIC(8,2) NOT NULL DEFAULT 0.00 CHECK (availability >= 0.00),
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production.product (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    product_number VARCHAR(25) NOT NULL,
    make_flag BOOLEAN NOT NULL DEFAULT TRUE,
    finished_goods_flag BOOLEAN NOT NULL DEFAULT TRUE,
    color VARCHAR(15),
    safety_stock_level SMALLINT NOT NULL CHECK (safety_stock_level > 0),
    reorder_point SMALLINT NOT NULL CHECK (reorder_point > 0),
    standard_cost NUMERIC(19,4) NOT NULL CHECK (standard_cost >= 0.00),
    list_price NUMERIC(19,4) NOT NULL CHECK (list_price >= 0.00),
    size VARCHAR(5),
    size_unit_measure_code CHAR(3),
    weight_unit_measure_code CHAR(3),
    weight NUMERIC(8,2) CHECK (weight > 0.00),
    days_to_manufacture INTEGER NOT NULL CHECK (days_to_manufacture >= 0),
    product_line CHAR(2) CHECK (UPPER(product_line) IN ('S','T','M','R') OR product_line IS NULL),
    class CHAR(2) CHECK (UPPER(class) IN ('L','M','H') OR class IS NULL),
    style CHAR(2) CHECK (UPPER(style) IN ('W','M','U') OR style IS NULL),
    product_subcategory_id INTEGER,
    product_model_id INTEGER,
    sell_start_date TIMESTAMP NOT NULL,
    sell_end_date TIMESTAMP,
    discontinued_date TIMESTAMP,
    rowguid UUID NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((sell_end_date >= sell_start_date) OR (sell_end_date IS NULL))
);

CREATE TABLE IF NOT EXISTS production.product_category (
    product_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    rowguid UUID NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production.product_subcategory (
    product_subcategory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_category_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    rowguid UUID NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production.scrap_reason (
    scrap_reason_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===========================
-- Sales Tables
-- ===========================

CREATE TABLE IF NOT EXISTS sales.country_region_currency (
    country_region_code VARCHAR(3) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.credit_card (
    credit_card_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_type VARCHAR(50) NOT NULL,
    card_number VARCHAR(25) NOT NULL,
    exp_month SMALLINT NOT NULL,
    exp_year SMALLINT NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.currency (
    currency_code CHAR(3) NOT NULL,
    name VARCHAR(50) NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.currency_rate (
    currency_rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_rate_date TIMESTAMP NOT NULL,
    from_currency_code CHAR(3) NOT NULL,
    to_currency_code CHAR(3) NOT NULL,
    average_rate NUMERIC(19,4) NOT NULL,
    end_of_day_rate NUMERIC(19,4) NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.customer (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER,
    store_id INTEGER,
    territory_id INTEGER,
    account_number VARCHAR(20),
    rowguid UUID NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.sales_order_header (
    sales_order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_number SMALLINT NOT NULL DEFAULT 0,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_date TIMESTAMP NOT NULL CHECK (due_date >= order_date),
    ship_date TIMESTAMP,
    status SMALLINT NOT NULL DEFAULT 1 CHECK (status BETWEEN 0 AND 8),
    online_order_flag BOOLEAN NOT NULL DEFAULT TRUE,
    purchase_order_number VARCHAR(25),
    account_number VARCHAR(25),
    carrier_tracking_number VARCHAR(25),
    customer_id INTEGER NOT NULL,
    salesperson_id INTEGER,
    territory_id INTEGER,
    bill_to_address_id INTEGER NOT NULL,
    ship_to_address_id INTEGER NOT NULL,
    ship_method_id INTEGER NOT NULL,
    credit_card_id INTEGER,
    credit_card_approval_code VARCHAR(15),
    currency_rate_id INTEGER,
    subtotal NUMERIC(19,4) NOT NULL DEFAULT 0.00 CHECK (subtotal >= 0.00),
    tax_amt NUMERIC(19,4) NOT NULL DEFAULT 0.00 CHECK (tax_amt >= 0.00),
    freight NUMERIC(19,4) NOT NULL DEFAULT 0.00 CHECK (freight >= 0.00),
    total_due NUMERIC(19,4),
    comment VARCHAR(128),
    rowguid UUID NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((ship_date >= order_date) OR (ship_date IS NULL)),
    CHECK ((subtotal + tax_amt + freight)=total_due)
);

CREATE TABLE IF NOT EXISTS sales.sales_order_detail (
    sales_order_id INTEGER NOT NULL,
    sales_order_detail_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_tracking_number VARCHAR(25),
    order_qty SMALLINT NOT NULL CHECK (order_qty > 0),
    product_id INTEGER NOT NULL,
    special_offer_id INTEGER NOT NULL,
    unit_price NUMERIC(19,4) NOT NULL CHECK (unit_price >= 0.00),
    unit_price_discount NUMERIC(19,4) NOT NULL DEFAULT 0.00 CHECK (unit_price_discount >= 0.00),
    rowguid UUID NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.sales_tax_rate (
    sales_tax_rate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_province_id INTEGER NOT NULL,
    tax_type SMALLINT NOT NULL CHECK (tax_type BETWEEN 1 AND 3),
    tax_rate NUMERIC(10,4) NOT NULL DEFAULT 0.00,
    name VARCHAR(50) NOT NULL,
    rowguid UUID NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.sales_territory (
    territory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    country_region_code VARCHAR(3) NOT NULL,
    "group" VARCHAR(50) NOT NULL,
    sales_ytd NUMERIC(19,4) NOT NULL DEFAULT 0.00 CHECK (sales_ytd >= 0.00),
    sales_last_year NUMERIC(19,4) NOT NULL DEFAULT 0.00 CHECK (sales_last_year >= 0.00),
    cost_ytd NUMERIC(19,4) NOT NULL DEFAULT 0.00 CHECK (cost_ytd >= 0.00),
    cost_last_year NUMERIC(19,4) NOT NULL DEFAULT 0.00 CHECK (cost_last_year >= 0.00),
    rowguid UUID NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.sales_reason (
    sales_reason_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    reason_type VARCHAR(50) NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===========================
-- HumanResources Tables
-- ===========================

CREATE TABLE humanresources.employee (
    employee_id INTEGER NOT NULL,
    national_id_number VARCHAR(15) NOT NULL,
    login_id VARCHAR(256) NOT NULL,
    leader_id INTEGER,
    job_title VARCHAR(50) NOT NULL,
    birth_date DATE NOT NULL,
    marital_status CHAR(1) NOT NULL CHECK (UPPER(marital_status) IN ('M', 'S')),
    gender CHAR(1) NOT NULL CHECK (UPPER(gender) IN ('M', 'F')),
    hire_date DATE NOT NULL,
    salaried_flag BOOLEAN NOT NULL DEFAULT TRUE,
    vacation_hours SMALLINT NOT NULL DEFAULT 0 CHECK (vacation_hours BETWEEN -40 AND 240),
    sick_leave_hours SMALLINT NOT NULL DEFAULT 0 CHECK (sick_leave_hours BETWEEN 0 AND 120),
    current_flag BOOLEAN NOT NULL DEFAULT TRUE,
    rowguid UUID NOT NULL DEFAULT gen_random_uuid(),
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (birth_date BETWEEN DATE '1930-01-01' AND (CURRENT_DATE - INTERVAL '18 years')),
    CHECK (hire_date BETWEEN DATE '1996-07-01' AND (CURRENT_DATE + INTERVAL '1 day'))
);

CREATE TABLE IF NOT EXISTS humanresources.department (
    department_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    group_name VARCHAR(50) NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS humanresources.shift (
    shift_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE humanresources.employee_department_history (
    employee_id INTEGER NOT NULL,
    department_id SMALLINT NOT NULL,
    shift_id SMALLINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((end_date >= start_date) OR (end_date IS NULL))
);

CREATE TABLE humanresources.employee_pay_history (
    employee_id INTEGER NOT NULL,
    rate_change_date TIMESTAMP NOT NULL,
    rate NUMERIC(19,4) NOT NULL CHECK (rate BETWEEN 6.50 AND 200.00),
    pay_frequency SMALLINT NOT NULL CHECK (pay_frequency IN (1, 2)), -- 1 = monthly, 2 = biweekly
    modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);